# generated by wxGlade 0.5cvs on Fri Aug  3 21:56:01 2007 from /home/jv/src/eekboek/src/wxeb/wxeb.wxg
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package EB::Wx::Shell::MainFrame;

use EekBoek;
use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;
use utf8;

# begin wxGlade: ::dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

use EB::Wx::Shell::HtmlViewer;
use EB::Wx::Shell::PreferencesDialog;
use Wx::Perl::ProcessStream qw[:everything];

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: EB::Wx::Shell::MainFrame::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{s_input_staticbox} = Wx::StaticBox->new($self, -1, _T("Input") );
	

	# Menu Bar

	$self->{menubar} = Wx::MenuBar->new();
	use constant MENU_REP_TRIAL => Wx::NewId();
	use constant MENU_REP_BAL => Wx::NewId();
	use constant MENU_REP_RES => Wx::NewId();
	use constant MENU_REP_JNL => Wx::NewId();
	use constant MENU_REP_UN => Wx::NewId();
	use constant MENU_REP_AP => Wx::NewId();
	use constant MENU_REP_AR => Wx::NewId();
	my $wxglade_tmp_menu;
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_OPEN, _T("&Open\tCtrl-O"), "");
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(wxID_PREFERENCES, _T("Prefere&nces..."), "");
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(wxID_EXIT, _T("E&xit\tCtrl-Q"), "");
	$self->{_T("menubar")}->Append($wxglade_tmp_menu, _T("&File"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_CLEAR, _T("&Clear output"), "");
	$self->{_T("menubar")}->Append($wxglade_tmp_menu, _T("&Edit"));
	$self->{_T("Reports")} = Wx::Menu->new();
	$self->{_T("Reports")}->Append(MENU_REP_TRIAL, _T("&Trial"), "");
	$self->{_T("Reports")}->Append(MENU_REP_BAL, _T("&Balance"), "");
	$self->{_T("Reports")}->Append(MENU_REP_RES, _T("&Results"), "");
	$self->{_T("Reports")}->AppendSeparator();
	$self->{_T("Reports")}->Append(MENU_REP_JNL, _T("&Journal"), "");
	$self->{_T("Reports")}->AppendSeparator();
	$self->{_T("Reports")}->Append(MENU_REP_UN, _T("&Unsettled Accounts"), "");
	$self->{_T("Reports")}->AppendSeparator();
	$self->{_T("Reports")}->Append(MENU_REP_AP, _T("Accounts &Payable"), "");
	$self->{_T("Reports")}->Append(MENU_REP_AR, _T("Accounts Re&ceivable"), "");
	$self->{_T("menubar")}->Append($self->{_T("Reports")}, _T("&Reports"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_ABOUT, _T("&About..."), "");
	$self->{_T("menubar")}->Append($wxglade_tmp_menu, _T("&Help"));
	$self->SetMenuBar($self->{menubar});
	
# Menu Bar end

	$self->{statusbar} = $self->CreateStatusBar(1, wxST_SIZEGRIP);
	$self->{t_output} = Wx::TextCtrl->new($self, -1, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxHSCROLL);
	$self->{t_input} = Wx::TextCtrl->new($self, -1, "", wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_PROCESS_TAB|wxHSCROLL);
	$self->{b_send} = Wx::Button->new($self, -1, _T("Send"));

	$self->__set_properties();
	$self->__do_layout();

	Wx::Event::EVT_MENU($self, wxID_OPEN, \&OnOpen);
	Wx::Event::EVT_MENU($self, wxID_PREFERENCES, \&OnPrefs);
	Wx::Event::EVT_MENU($self, wxID_EXIT, \&OnQuit);
	Wx::Event::EVT_MENU($self, wxID_CLEAR, \&OnClear);
	Wx::Event::EVT_MENU($self, MENU_REP_TRIAL, \&OnTrial);
	Wx::Event::EVT_MENU($self, MENU_REP_BAL, \&OnMenuBal);
	Wx::Event::EVT_MENU($self, MENU_REP_RES, \&OnMenuRes);
	Wx::Event::EVT_MENU($self, MENU_REP_JNL, \&OnJournal);
	Wx::Event::EVT_MENU($self, MENU_REP_UN, \&OnMenuUns);
	Wx::Event::EVT_MENU($self, MENU_REP_AP, \&OnMenuAP);
	Wx::Event::EVT_MENU($self, MENU_REP_AR, \&OnMenuAR);
	Wx::Event::EVT_MENU($self, wxID_ABOUT, \&OnAbout);
	Wx::Event::EVT_TEXT_ENTER($self, $self->{t_input}->GetId, \&OnTextEnter);
	Wx::Event::EVT_BUTTON($self, $self->{b_send}->GetId, \&OnSend);

# end wxGlade

	Wx::Event::EVT_CHAR($self->{t_input}, sub { $self->OnChar(@_) });
#	Wx::Event::EVT_IDLE($self, \&OnIdle);

	EVT_WXP_PROCESS_STREAM_STDOUT( $self, \&evt_process_stdout);
	EVT_WXP_PROCESS_STREAM_STDERR( $self, \&evt_process_stderr);
	EVT_WXP_PROCESS_STREAM_EXIT( $self, \&evt_process_exit);

	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: EB::Wx::Shell::MainFrame::__set_properties

	$self->SetTitle(_T("EekBoek"));
	$self->SetSize(Wx::Size->new(800, 550));
	$self->{statusbar}->SetStatusWidths(-1);
	
	my( @statusbar_fields ) = (
		""
	);

	if( @statusbar_fields ) {
		$self->{statusbar}->SetStatusText($statusbar_fields[$_], $_) 	
		for 0 .. $#statusbar_fields ;
	}
	$self->{t_input}->SetFocus();

# end wxGlade

	my $f = Wx::SystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
	$self->{t_output}->SetFont(Wx::Font->new($f->GetPointSize, wxMODERN, wxNORMAL, wxNORMAL, 0, ""));

}

sub __do_layout {
	my $self = shift;

# begin wxGlade: EB::Wx::Shell::MainFrame::__do_layout

	$self->{s_main} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{s_layout} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{s_input}= Wx::StaticBoxSizer->new($self->{s_input_staticbox}, wxHORIZONTAL);
	$self->{s_output} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{s_output}->Add($self->{t_output}, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{s_layout}->Add($self->{s_output}, 1, wxEXPAND, 0);
	$self->{s_input}->Add($self->{t_input}, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{s_input}->Add(5, 1, 0, wxADJUST_MINSIZE, 0);
	$self->{s_input}->Add($self->{b_send}, 0, wxADJUST_MINSIZE, 0);
	$self->{s_layout}->Add($self->{s_input}, 0, wxEXPAND, 0);
	$self->{s_main}->Add($self->{s_layout}, 1, wxALL|wxEXPAND, 5);
	$self->SetSizer($self->{s_main});
	$self->Layout();
	$self->SetSize(Wx::Size->new(800, 550));

# end wxGlade
}

sub RunCommand {
    my ($self, $cmd) = @_;
    unless ( defined $self->{_proc} ) {
	unless ( $self->{_ebcfg} && -s $self->{_ebcfg} ) {
	    my $md = Wx::MessageDialog->new
	      ($self,
	       _T("Please select a valid .eekboek.conf first"),
	       _T("Missing config"), wxOK|wxICON_INFORMATION,
	       wxDefaultPosition);
	    $md->ShowModal;
	    $md->Destroy;
	    $self->OnOpen;
	    return;
	}
	my @eb = qw(ebshell --nointeractive);
	push(@eb, "-f", $self->{_ebcfg}) if $self->{_ebcfg};
	$self->{_proc} =
	  Wx::Perl::ProcessStream->OpenProcess(\@eb, 'EekBoek', $self);
	$self->{_pid} =	$self->{_proc}->GetProcessId;
	warn("STARTED: @eb\n");
    }

    $cmd = "database" unless defined $cmd;
    $self->{t_output}->AppendText("eb> ");
    $self->ShowText($cmd, wxBLUE);
    if ( $cmd =~ /^(balans|result|proefensaldibalans|journaal|openstaand|(?:deb|cred)iteuren)(?:\s|$)/ ) {
	$cmd .= " --gen-wxhtml";
    }
    $self->{_proc}->WriteProcess($cmd."\n");
}

sub ShowText {
    my ($self, $text, $colour) = @_;
    if ( $colour ) {
	my $t = Wx::TextAttr->new;
	$t->SetTextColour($colour);
	my $x0 = $self->{t_output}->GetLastPosition;
	$self->{t_output}->AppendText($text."\n");
	$self->{t_output}->SetStyle($x0, $self->{t_output}->GetLastPosition, $t);
    }
    else {
	$self->{t_output}->AppendText($text."\n");
    }
}

my $capturing;
sub evt_process_stdout {
    my ($self, $event) = @_;
    #$event->Skip(1);
    my $out = $event->GetLine;
    # warn("app: $out\n");
    if ( $capturing || $out eq "<html>" ) {
	$capturing .= $out . "\n";
	if ( $out eq "</html>" ) {
	    my ($title) = ($capturing =~ m{<title>(.+?)</title>});
	    #warn("captured $title: ", length($capturing), " characters\n");
	    my $panel = $self->{prefs_repwin} ? "d_htmlpanel" : "d_htmlpanel_$title";
	    $self->{$panel} ||= EB::Wx::Shell::HtmlViewer->new
	      ($self, -1, $title);
	    $self->{$panel}->html->SetPage($capturing);
	    $self->{$panel}->htmltext = $capturing;
	    $self->{$panel}->SetTitle($title);
	    $self->{$panel}->Show(1);
	    $capturing = "";
	}
    }
    else {
	$self->{t_output}->AppendText($out."\n");
    }
}

sub evt_process_stderr {
    my ($self, $event) = @_;
    #$event->Skip(1);
    my $out = $event->GetLine;
    $self->ProcessMessages($out);
}

sub evt_process_exit {
    my ($self, $event) = @_;
    #$event->Skip(1);
    my $process = $event->GetProcess;
    my $pid = $process->GetProcessId;
    #my $line = $event->GetLine;
    #my @buffers = @{ $process->GetStdOutBuffer };
    #my @errors = @{ $process->GetStdOutBuffer };
    #my $exitcode = $process->GetExitCode;
    return if $self->{_pid} && $self->{_pid} != $pid;
    $process->Destroy;
    my $md = Wx::MessageDialog->new
      ($self,
       _T("EekBoek program has finished"),
       _T("Finished"), wxOK|wxICON_INFORMATION,
       wxDefaultPosition);
    $md->ShowModal;
    $md->Destroy;
    $self->OnQuit;
}

sub ProcessMessages {
    my ($self, $err) = @_;
    return unless $err;
    my @err = split(/\n+/, $err);
    while ( @err ) {
	$err = shift(@err);
	if ( $err =~ /^(EekBoek\s+([0-9.]+).*)/ ) {
	    $self->{statusbar}->SetStatusText($1, 0);
	    $self->{_eb} = $2;
	    next;
	}
	my @i;
	if ( $err =~ /^\?+(.*)/ ) {
	    $self->ShowText($err, wxRED);
	    next unless $self->{prefs_errorpopup};
	    @i = ($1, "Error", wxOK|wxICON_ERROR);
	}
	elsif ( $err =~ /^\!+(.*)/ ) {
	    $self->ShowText($err, Wx::Colour->new("magenta"));
	    next unless $self->{prefs_warnpopup};
	    @i = ($1, "Warning", wxOK|wxICON_WARNING);
	}
	else {
	    $self->ShowText($err, wxGREEN);
	    next unless $self->{prefs_infopopup};
	    @i = ($err, "Information", wxOK|wxICON_INFORMATION);
	}
	my $md = Wx::MessageDialog->new($self, @i, wxDefaultPosition);
	$md->ShowModal;
	$md->Destroy;
    }
}


sub OnTextEnter {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnTextEnter <event_handler>

	my $cmd = $self->{t_input}->GetValue;
	return unless $cmd;
	push(@{$self->{_cmd}}, $cmd)
	  unless $cmd eq $self->{_cmd}->[-1];
	$self->{_cmdptr} = $#{$self->{_cmd}} + 1;
	$self->{t_input}->SetValue("");
	$self->RunCommand($cmd);
	$self->{t_input}->SetFocus();

# end wxGlade
}

sub OnSend {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnSend <event_handler>

	&OnTextEnter;

# end wxGlade
}

sub OnOpen {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnOpen <event_handler>

	my $fd = Wx::FileDialog->new
	  ($self,
	   _T("Choose"),
	   "", "",
	   ".eekboek.conf",
	   0|wxFD_FILE_MUST_EXIST,
	   wxDefaultPosition);
	my $ret = $fd->ShowModal;
	if ( $ret == wxID_OK ) {
	    if ( $self->{_proc} ) {
		$self->{_proc}->TerminateProcess;
		undef $self->{_proc};
		undef $self->{_pid};
	    }
	    $self->{_ebcfg} = $fd->GetPath;
	    $self->RunCommand(undef);
	}
	$fd->Destroy;

# end wxGlade
}

sub OnQuit {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnQuit <event_handler>
	$self->SaveHistory;
	$self->Destroy;

# end wxGlade
}

sub PutOnHistory {
    my ($self, $cmd) = @_;
    return if $cmd eq "";
    return if @{$self->{_cmd}} && $cmd eq $self->{_cmd}->[-1];

    return if exists $self->{_cmd}->[$self->{_cmdptr}]
      && $cmd eq $self->{_cmd}->[$self->{_cmdptr}];

    push(@{$self->{_cmd}}, $cmd);
}

use Wx qw(:keycode);

sub OnChar {
    my ($self, $ctl, $event) = @_;

    # Get key code and char, if ordinary.
    my $k = $event->GetKeyCode;
    my $c = ($k < WXK_START) ? pack("C", $k) : "";

    if ( $k == WXK_UP
	 && $self->{_cmdptr} > 0 ) {
	$self->PutOnHistory($ctl->GetValue);
	$ctl->SetValue($self->{_cmd}->[--$self->{_cmdptr}]);
	$ctl->SetInsertionPointEnd;
    }
    elsif ( $k == WXK_DOWN
	 && $self->{_cmdptr} < $#{$self->{_cmd}} ) {
	$self->PutOnHistory($ctl->GetValue);
	$ctl->SetValue($self->{_cmd}->[++$self->{_cmdptr}]);
	$ctl->SetInsertionPointEnd;
    }
    elsif (
	 $k == WXK_TAB     ||
	 $k == WXK_RETURN  ||
	 $k >= WXK_START   ||
	 $event->HasModifiers
       ) {
	# Common controls.
	$event->Skip;
	return;
    }
    else {
	$event->Skip;
    }
}


sub OnAbout {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnAbout <event_handler>

	my $year = 1900 + (localtime(time))[5];

	my $md = Wx::MessageDialog->new
	  ($self,
	   "$EekBoek::PACKAGE WxShell version $EekBoek::VERSION\n".
	   "Copyright 2007-$year Squirrel Consultancy\n\n".
	   "Written by Johan Vromans\n".
	   "<jvromans\@squirrel.nl>\n".
	   "http://www.squirrel.nl\n\n".
	   "GUI design with wxGlade, http://wxglade.sourceforge.net\n\n".
	   "Perl version ".sprintf("%vd",$^V)."\n".
	   "WxPerl version $Wx::VERSION\n".
	   "wxWidgets version ".Wx::wxVERSION."\n",
	   "About EekBoek WxShell",
	   wxOK|wxICON_INFORMATION,
	   wxDefaultPosition);
	$md->ShowModal;
	$md->Destroy;

# end wxGlade
}


sub OnClear {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnClear <event_handler>

	$self->{t_output}->SetValue("");

# end wxGlade
}


sub OnPrefs {
    my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnPrefs <event_handler>
    $self->{d_prefs} ||= EB::Wx::Shell::PreferencesDialog->new($self, -1, "Preferences");
    for ( qw(repwin errorpopup warnpopup infopopup) ) {
	$self->{d_prefs}->{"cx_$_"}->SetValue( $self->{"prefs_$_"} );
    }
    $self->{d_prefs}->Show(1);
# end wxGlade
}


sub FillHistory {
    my ($self, $histfile) = @_;
    $self->{_histfile} = $histfile;
    $self->{_cmd} = [];
    $self->{_cmdptr} = 0;
    if ( -s $histfile ) {
	my $fh;
	return unless open($fh, "<", $histfile);
	while ( <$fh> ) {
	    chomp;
	    $self->PutOnHistory($_);
	}
	close($fh);
    }
    $self->{_cmdinit} = $self->{_cmdptr} = $#{$self->{_cmd}} + 1;
}


sub SaveHistory {
    my $self = shift;
    my $fh;
    my $histfile = $self->{_histfile};
    return unless open($fh, ">>", $histfile);
    while ( $self->{_cmdinit} < $self->{_cmdptr} ) {
	print { $fh } ($self->{_cmd}->[$self->{_cmdinit}], "\n");
	$self->{_cmdinit}++;
    }
    close($fh);

    my $conf = Wx::ConfigBase::Get;
    for ( qw(repwin errorpopup warnpopup infopopup) ) {
	$conf->WriteBool( "prefs_$_", $self->{"prefs_$_"} );
    }

}


sub OnMenuBal {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnMenuBal <event_handler>

	$self->{_proc}->WriteProcess("balans --gen-wxhtml\n");

# end wxGlade
}


sub OnMenuRes {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnMenuRes <event_handler>

	$self->{_proc}->WriteProcess("result --gen-wxhtml\n");

# end wxGlade
}


sub OnMenuAP {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnMenuAP <event_handler>

	$self->{_proc}->WriteProcess("crediteuren --gen-wxhtml\n");

# end wxGlade
}


sub OnMenuAR {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnMenuAR <event_handler>

	$self->{_proc}->WriteProcess("debiteuren --gen-wxhtml\n");

# end wxGlade
}


sub OnMenuUns {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnMenuUns <event_handler>

	$self->{_proc}->WriteProcess("openstaand --gen-wxhtml\n");

# end wxGlade
}


sub OnTrial {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnTrial <event_handler>

	$self->{_proc}->WriteProcess("proefensaldibalans --gen-wxhtml\n");

# end wxGlade
}


sub OnJournal {
	my ($self, $event) = @_;
# wxGlade: EB::Wx::Shell::MainFrame::OnJournal <event_handler>

	$self->{_proc}->WriteProcess("journaal --gen-wxhtml\n");

# end wxGlade
}

# end of class EB::Wx::Shell::MainFrame

1;

