-- Constants

CREATE TABLE Constants (
    name	text not null primary key,
    value	int
);

COMMENT ON TABLE Constants IS
  'This is generated from EB::Globals. DO NOT CHANGE.';

COPY Constants (name, value) FROM stdin;
AMTPRECISION	2
AMTSCALE	100
AMTWIDTH	9
BTWPER_GEEN	0
BTWPER_HALFJAAR	2
BTWPER_JAAR	1
BTWPER_KWARTAAL	4
BTWPER_TRIMESTER	3
BTWPRECISION	4
BTWSCALE	10000
BTWTYPE_GEEN	0
BTWTYPE_HOOG	1
BTWTYPE_LAAG	2
BTWWIDTH	5
BTW_EXTRA	3
BTW_INTRA	2
BTW_NORMAAL	0
BTW_VERLEGD	1
DBKTYPE_BANK	3
DBKTYPE_INKOOP	1
DBKTYPE_KAS	4
DBKTYPE_MEMORIAAL	5
DBKTYPE_VERKOOP	2
SCM_MAJVERSION	1
SCM_MINVERSION	0
SCM_REVISION	0
\.
