#! perl

use strict;
# use lib qw(EekBoekLibrary);

=head1 NAME

EekBoek - Bookkeeping software for small and medium-size businesses

=head1 SYNOPSIS

  ebshell

EekBoek is a bookkeeping package for small and medium-size businesses.
Unlike other accounting software, EekBoek has both a command-line
interface (CLI) and a graphical user-interface (GUI). Furthermore, it
has a complete Perl API to create your own custom applications.

EekBoek is designed for the Dutch/European market and currently
available in Dutch only. An English translation is in the works (help
appreciated).

=head1 DESCRIPTION

For a description how to use the program, see L<http://www.eekboek.nl/docs/index.html>.

=head1 BUGS AND PROBLEMS

Please use the eekboek-users mailing list at SourceForge.

=head1 AUTHOR AND CREDITS

Johan Vromans (jvromans@squirrel.nl) wrote this package.

Web site: L<http://www.eekboek.nl>.

=head1 COPYRIGHT AND DISCLAIMER

This program is Copyright 2005-2009 by Squirrel Consultancy. All
rights reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of either: a) the GNU General Public License as
published by the Free Software Foundation; either version 1, or (at
your option) any later version, or b) the "Artistic License" which
comes with Perl.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See either the
GNU General Public License or the Artistic License for more details.

=cut

package main;

use strict;
use warnings;
use File::Spec;
use File::Basename;

use Encode;
binmode( STDERR, ':encoding(utf-8)' );

# Common case when run from unpacked dist.
my $script = $0;
if ( -s File::Spec->catfile( dirname( dirname ($script) ), "lib", "EekBoek.pm" ) ) {
    unshift( @INC, File::Spec->catfile( dirname( dirname ($script) ), "lib" ) );
}

# Check EekBoek install.
error( "EekBoek is niet geïnstalleerd, of kon niet worden gevonden.\n".
       "\nRaadplaag uw systeembeheerder.\n",
       "Installatiefout" )
  unless findfile( "EekBoek.pm" )
  &&     findfile( "EB.pm" )
  &&     findfile( "EB/schema/eekboek.sql" );

require EekBoek;

error( "De geïnstalleerde versie van $EekBoek::PACKAGE is niet toereikend.\n".
       "Versie $EekBoek::VERSION is geïnstalleerd terwijl versie 1.05.00 of later\n".
       "is vereist.\n".
       "\nRaadplaag uw systeembeheerder.",
       "Installatiefout" )
  unless $EekBoek::VERSION ge "1.05.00";

require EB::Config;
EB::Config->import( $EekBoek::PACKAGE );
require EB;
EB->import;
require EB::Main;
EB::Main->run;

################ Subroutines ################

sub findfile {
    my ( $file ) = @_;
    foreach ( @INC ) {
	my $f = File::Spec->catfile( $_, $file );
	return $f if -s $f;
    }
    return;
}

################ Messengers ################

sub error {
    my ( $msg, $caption, $style ) = @_;
    warn( encode_utf8($caption), "\n",
	  encode_utf8($msg), "\n" );
    exit(1);
}

1;

# $Id: ebshell,v 1.19 2009/10/09 15:45:52 jv Exp $
