#!/bin/sh

GTF="-j -k__x -k__n -k__xn -k__nx -k_ -k_T -kN__ --from-code=ISO-8859-15"
DIR="po"
LIB="lib"
cd ..
if [ "$1" = "regen" ]
then
    cp /dev/null $DIR/ebcore.pot || exit 1
    cp /dev/null $DIR/ebgui.pot || exit 1

    find ebshell.pl -exec xgettext $GTF -o $DIR/ebcore.pot {} \;
    find lib/EB.pm lib/EB \( -name CVS -prune \) -o \( -name '*.pm' -exec xgettext $GTF -o $DIR/ebcore.pot {} \; \)

    find GUI/eb.pl -exec xgettext $GTF -o $DIR/ebgui.pot {} \;
    find GUI \( -name CVS -prune \) -o \( -name '*.pm' -exec xgettext $GTF -o $DIR/ebgui.pot {} \; \)
fi

for pkg in core gui
do
  for locale in en
  do
    if [ -f $DIR/eb${pkg}-${locale}.po ]
    then
	# Update current .po:
	msgmerge -U $DIR/eb${pkg}-${locale}.po $DIR/eb${pkg}.pot
	# Compile it:
	msgfmt -c -v -o $LIB/EB/locale/${locale}/LC_MESSAGES/eb${pkg}.mo $DIR/eb${pkg}-${locale}.po
    else
	# Create a .po for translation:
	if [ $locale = "en" ]
	then
	    cat $DIR/eb${pkg}-${locale}.pox $DIR/eb${pkg}.pot > $DIR/eb${pkg}-${locale}.po 
	else
	    msginit -i $DIR/eb${pkg}.pot -o $DIR/eb${pkg}.po -l $locale --no-translator
        fi
    fi
  done
done
