# generated by wxGlade 0.4cvs on Mon Aug  1 17:59:21 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

package main;

our $config;
our $dbh;

use Wx 0.15 qw[:allclasses];
use strict;
package EB::Wx::MainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;
use EB;

# begin wxGlade: ::dependencies
# end wxGlade

my %cmds;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: EB::Wx::MainFrame::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	

	# Menu Bar

	$self->{mainframe_menubar} = Wx::MenuBar->new();
	$self->SetMenuBar($self->{mainframe_menubar});
	use constant MENU_NEW => Wx::NewId();
	use constant MENU_EXPORT => Wx::NewId();
	use constant MENU_IMPORT => Wx::NewId();
	use constant MENU_PROPS => Wx::NewId();
	use constant MENU_LOGW => Wx::NewId();
	use constant MENU_LOGCLEAN => Wx::NewId();
	use constant MENU_RESTART => Wx::NewId();
	use constant MENU_PREFS => Wx::NewId();
	use constant MENU_GBK => Wx::NewId();
	use constant MENU_REL => Wx::NewId();
	use constant MENU_BTW => Wx::NewId();
	use constant MENU_STD => Wx::NewId();
	use constant MENU_R_PRF => Wx::NewId();
	use constant MENU_R_BAL => Wx::NewId();
	use constant MENU_R_RES => Wx::NewId();
	use constant MENU_R_GBK => Wx::NewId();
	use constant MENU_R_JNL => Wx::NewId();
	use constant MENU_R_BTW => Wx::NewId();
	use constant MENU_R_OP => Wx::NewId();
	use constant MENU_R_DEB => Wx::NewId();
	use constant MENU_R_CRD => Wx::NewId();
	use constant MENU_DOC => Wx::NewId();
	my $wxglade_tmp_menu;
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_NEW, _T("Nieuw ...\tCtrl-N"), _T("Aanmaken nieuwe administratie"));
	$wxglade_tmp_menu->Append(MENU_NEW, _T("Nieuw (Wizard) ..."), _T("Test wizard"));
	$wxglade_tmp_menu->Append(wxID_OPEN, _T("Open ...\tCtrl-O"), _T("Open een bestaande administratie"));
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_EXPORT, _T("Export ..."), _T("Exporteer administratie"));
	$wxglade_tmp_menu->Append(MENU_IMPORT, _T("Import ..."), _T("Importeer administratie"));
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_PROPS, _T("Eigenschappen ...\tAlt+Enter"), _T("Toon administratiegegevens"));
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_LOGW, _T("Verberg log venster"), _T("Toon of verberg het log venster"));
	$wxglade_tmp_menu->Append(MENU_LOGCLEAN, _T("Log venster schoonmaken"), "");
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_RESTART, _T("Opnieuw starten\tAlt-R"), _T("Herstart (voor testen)"));
	$wxglade_tmp_menu->Append(wxID_EXIT, _T("Beëndigen\tAlt-x"), _T("Beëindig het programma"));
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("&Bestand"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_CUT, _T("Knip"), "");
	$wxglade_tmp_menu->Append(wxID_PASTE, _T("Plak"), "");
	$wxglade_tmp_menu->Append(wxID_COPY, _T("Kopiëer"), "");
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_PREFS, _T("Instellingen"), _T("Instellingen"));
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("&Edit"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(MENU_GBK, _T("Grootboekrekeningen"), _T("Onderhoud rekeningschema en grootboekrekeningen"));
	$wxglade_tmp_menu->Append(MENU_REL, _T("Relaties"), _T("Onderhoud debiteuren en crediteuren"));
	$wxglade_tmp_menu->Append(MENU_BTW, _T("BTW Tarieven"), _T("Onderhoud BTW tarieven"));
	$wxglade_tmp_menu->Append(MENU_STD, _T("Koppelingen"), _T("Onderhoud Standaardrekeningen (koppelingen)"));
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("&Onderhoud"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("&Dagboeken"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(MENU_R_PRF, _T("Proef- en Saldibalans"), _T("Opmaken Proef- en Saldibalans"));
	$wxglade_tmp_menu->Append(MENU_R_BAL, _T("Balans"), _T("Opmaken Balans"));
	$wxglade_tmp_menu->Append(MENU_R_RES, _T("Resultaatrekening"), _T("Opmaken Resultaatrekening"));
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_R_GBK, _T("Grootboek"), _T("Opmaken Grootboekrapportage"));
	$wxglade_tmp_menu->Append(MENU_R_JNL, _T("Journaal"), _T("Opmaken Journaal"));
	$wxglade_tmp_menu->Append(MENU_R_BTW, _T("BTW aangifte"), _T("Opmaken BTW aangifte"));
	$wxglade_tmp_menu->AppendSeparator();
	$wxglade_tmp_menu->Append(MENU_R_OP, _T("Openstaande posten"), _T("Opmaken overzicht openstaande posten"));
	$wxglade_tmp_menu->Append(MENU_R_DEB, _T("Debiteuren"), _T("Opmaken Debiteurenoverzicht"));
	$wxglade_tmp_menu->Append(MENU_R_CRD, _T("Crediteuren"), _T("Opmaken Crediteurenoverzicht"));
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("Ra&pportages"));
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(MENU_DOC, _T("Documentatie\tF1"), _T("Toon de EekBoek documentatie"));
	$wxglade_tmp_menu->Append(wxID_ABOUT, _T("&Info"), _T("Informatie"));
	$self->{mainframe_menubar}->Append($wxglade_tmp_menu, _T("&Hulp"));
	
# Menu Bar end

	$self->{mainframe_statusbar} = $self->CreateStatusBar(1, 0);
	$self->{eb_logo} = Wx::StaticBitmap->new($self, -1, Wx::Bitmap->new("eb.jpg", wxBITMAP_TYPE_ANY), wxDefaultPosition, wxDefaultSize, wxDOUBLE_BORDER);
	$self->{pp_logo} = Wx::StaticBitmap->new($self, -1, Wx::Bitmap->new("perl_powered.png", wxBITMAP_TYPE_ANY), wxDefaultPosition, wxDefaultSize, );
	$self->{tx_log} = Wx::TextCtrl->new($self, -1, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxHSCROLL);

	$self->__set_properties();
	$self->__do_layout();

	Wx::Event::EVT_MENU($self, wxID_NEW, \&OnNew);
	Wx::Event::EVT_MENU($self, MENU_NEW, \&OnNewWiz);
	Wx::Event::EVT_MENU($self, wxID_OPEN, \&OnOpen);
	Wx::Event::EVT_MENU($self, MENU_EXPORT, \&OnExport);
	Wx::Event::EVT_MENU($self, MENU_IMPORT, \&OnImport);
	Wx::Event::EVT_MENU($self, MENU_PROPS, \&OnProperties);
	Wx::Event::EVT_MENU($self, MENU_LOGW, \&OnLogw);
	Wx::Event::EVT_MENU($self, MENU_LOGCLEAN, \&OnLogClean);
	Wx::Event::EVT_MENU($self, MENU_RESTART, \&OnRestart);
	Wx::Event::EVT_MENU($self, wxID_EXIT, \&OnExit);
	Wx::Event::EVT_MENU($self, MENU_PREFS, \&OnPreferences);
	Wx::Event::EVT_MENU($self, MENU_GBK, \&OnMGbk);
	Wx::Event::EVT_MENU($self, MENU_REL, \&OnMRel);
	Wx::Event::EVT_MENU($self, MENU_BTW, \&OnMBtw);
	Wx::Event::EVT_MENU($self, MENU_STD, \&OnMStdAcc);
	Wx::Event::EVT_MENU($self, MENU_R_PRF, \&OnRPrf);
	Wx::Event::EVT_MENU($self, MENU_R_BAL, \&OnRBal);
	Wx::Event::EVT_MENU($self, MENU_R_RES, \&OnRRes);
	Wx::Event::EVT_MENU($self, MENU_R_GBK, \&OnRGbk);
	Wx::Event::EVT_MENU($self, MENU_R_JNL, \&OnRJnl);
	Wx::Event::EVT_MENU($self, MENU_R_BTW, \&OnRBtw);
	Wx::Event::EVT_MENU($self, MENU_R_OP, \&OnROpen);
	Wx::Event::EVT_MENU($self, MENU_R_DEB, \&OnRDeb);
	Wx::Event::EVT_MENU($self, MENU_R_CRD, \&OnRCrd);
	Wx::Event::EVT_MENU($self, MENU_DOC, \&OnDoc);
	Wx::Event::EVT_MENU($self, wxID_ABOUT, \&OnAbout);

# end wxGlade

	$self->{OLDLOG} = Wx::Log::SetActiveTarget (Wx::LogTextCtrl->new($self->{tx_log}));
	Wx::Log::SetTimestamp("%T");
	Wx::LogMessage("Administratie: " . $config->lastdb);

	$self->adapt_menus;

	use Wx::Event qw(EVT_CLOSE);

	EVT_CLOSE($self, \&OnExit);

	%cmds = ( open	 => wxID_OPEN,
		  new    => wxID_NEW,
		  prop	 => MENU_PROPS,
		  wiz    => MENU_NEW,
		  gbk	 => MENU_GBK,
		  rel	 => MENU_REL,
		  btw	 => MENU_BTW,
		  std	 => MENU_STD,
		  rbal	 => MENU_R_BAL,
		  rres	 => MENU_R_RES,
		  rprf	 => MENU_R_PRF,
		  rgbk	 => MENU_R_GBK,
		  jnl	 => MENU_R_JNL,
		  rbtw	 => MENU_R_BTW,
		  rdeb	 => MENU_R_DEB,
		  rcrd	 => MENU_R_CRD,
		  log	 => MENU_LOGW,
		  about	 => wxID_ABOUT,
	     );

	$self;
}

sub __set_properties {
	my $self = shift;

# begin wxGlade: EB::Wx::MainFrame::__set_properties

	$self->SetTitle(_T("EekBoek"));
	$self->SetBackgroundColour(Wx::Colour->new(255, 255, 255));
	$self->{mainframe_statusbar}->SetStatusWidths(-1);
	
	my( @mainframe_statusbar_fields ) = (
		_T("EekBoek © 2005 Squirrel Consultancy ­ Geen administratie geladen")
	);

	if( @mainframe_statusbar_fields ) {
		$self->{mainframe_statusbar}->SetStatusText($mainframe_statusbar_fields[$_], $_) 	
		for 0 .. $#mainframe_statusbar_fields ;
	}

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: EB::Wx::MainFrame::__do_layout

	$self->{sz_main} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_4}->Add(150, 20, 2, wxADJUST_MINSIZE, 0);
	$self->{sizer_4}->Add($self->{eb_logo}, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 40);
	$self->{sizer_4}->Add(20, 20, 1, wxADJUST_MINSIZE, 0);
	$self->{sizer_4}->Add($self->{pp_logo}, 0, wxRIGHT|wxTOP|wxBOTTOM|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 40);
	$self->{sizer_4}->Add(150, 20, 2, wxADJUST_MINSIZE, 0);
	$self->{sz_main}->Add($self->{sizer_4}, 1, wxEXPAND, 0);
	$self->{sz_main}->Add($self->{tx_log}, 1, wxALL|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->SetSizer($self->{sz_main});
	$self->{sz_main}->Fit($self);
	$self->Layout();

# end wxGlade
}

sub closehandler {
    my ($self) = @_;
    @{$config->mainw}{qw(xpos ypos xwidth ywidth)} = ($self->GetPositionXY, $self->GetSizeWH);

    # Explicitly destroy the hidden (but still alive!) dialogs.
    foreach ( qw(opendialog) ) {
	next unless $self->{"d_$_"};
	$self->{"d_$_"}->Destroy;
    }
}

sub command {
    my ($self, $cmd) = @_;
    use Wx qw(wxEVT_COMMAND_MENU_SELECTED);

    foreach ( split(":", $cmd) ) {
	if ( exists($cmds{$_}) ) {
	    Wx::PostEvent($self,
			  Wx::CommandEvent->new(wxEVT_COMMAND_MENU_SELECTED, $cmds{$_}));
	}
	else {
	    Wx::LogMessage("Unknown command: $_");
	}
    }

}

sub adapt_menus {
    my $self = shift;

    $self->{mainframe_menubar}->Enable(MENU_BTW,   $dbh->does_btw);
    $self->{mainframe_menubar}->Enable(MENU_R_BTW, $dbh->does_btw);

    my $sth = $dbh->sql_exec("SELECT dbk_id,dbk_desc,dbk_type".
			     " FROM Dagboeken".
			     " ORDER BY dbk_desc");

    use Wx::Event qw(EVT_MENU);

    my $tmp = Wx::Menu->new;
    while ( my $rr = $sth->fetchrow_arrayref ) {
	my ($id, $desc, $type) = @$rr;
	# This consumes Ids, but we do not expect to do this often.
	my $m = Wx::NewId();
	$tmp->Append($m, "$desc\tAlt-$id",
		     __x("Dagboek {dbk}", dbk => $desc)."\n");
	my $tp = qw(X IV IV BKM BKM BKM)[$type];
	my $cl = "EB::Wx::Booking::${tp}Panel";
	undef($self->{"d_dbkpanel$id"});
	EVT_MENU($self, $m,
		 sub { eval "require $cl";
		       die($@) if $@;
		       my $cfg = $config->get(lc($tp)."w");
		       $self->{"d_dbkpanel$id"} ||=
			 $cl->new($self, -1,
				  __x("Dagboek {dbk}", dbk => $desc)."\n",
				  [$cfg->{xpos}, $cfg->{ypos}],
				  [$cfg->{xwidth}, $cfg->{ywidth}]);
		       ### TODO: How to save/restore geometry?
		       $self->{"d_dbkpanel$id"}->init($id, $desc, $type);
		       $self->{"d_dbkpanel$id"}->Show(1);
		       $self->{"d_dbkpanel$id"}->SetSize([$cfg->{xwidth}, $cfg->{ywidth}]);
		   });
    }

    my $ix = $self->{mainframe_menubar}->FindMenu(_T("&Dagboeken"));
    $tmp = $self->{mainframe_menubar}->Replace
      ($ix, $tmp,
       $self->{mainframe_menubar}->GetLabelTop($ix));
    $tmp->Destroy if $tmp;
    $self->{mainframe_menubar}->Refresh;

    my $t = $::cfg->val(qw(database name));
    $t =~ s/^eekboek_//;
    ::set_status(__x("Administratie: {adm}",
		     adm => $t));
    $self->SetTitle(__x("EekBoek: {adm}",
			adm => $dbh->adm("name")));
}

sub DESTROY {
    my $self = shift;
    Wx::Log::SetActiveTarget($self->{OLDLOG})->Destroy;
}

################ Menu: File ################

# wxGlade: EB::Wx::MainFrame::OnNew <event_handler>
sub OnNew {
    my ($self, $event) = @_;
    require EB::Wx::Tools::NewDialog;
    foreach my $win ( grep(/^d_m\S+panel$/, keys(%$self)) ) {
	next unless $self->{$win};
	next unless $self->{$win}->IsShown;
	Wx::MessageBox("Er zijn nog onderhoudsvensters open op de huidige database.\n".
		       "Deze dienen eerst te worden gesloten.",
		       "Open vensters",
		       wxOK|wxICON_ERROR);
	return;
    }
    $self->{d_newdialog} ||= EB::Wx::Tools::NewDialog->new
      ($self, -1,
       "Nieuwe administratie",
       [$config->neww->{xpos},$config->neww->{ypos}],
       [$config->neww->{xwidth},$config->neww->{ywidth}],
      );
    $self->{d_newdialog}->SetSize([$config->neww->{xwidth},$config->neww->{ywidth}]);
    my $ret = $self->{d_newdialog}->ShowModal;
    $self->{d_newdialog}->Destroy;
    $self->{d_newdialog} = undef;
    $self->adapt_menus;
}

# wxGlade: EB::Wx::MainFrame::OnNewWiz <event_handler>
sub OnNewWiz {
    my ($self, $event) = @_;
    require EB::Wx::Tools::NewDialogWiz;
    foreach my $win ( grep(/^d_m\S+panel$/, keys(%$self)) ) {
	next unless $self->{$win};
	next unless $self->{$win}->IsShown;
	Wx::MessageBox("Er zijn nog onderhoudsvensters open op de huidige database.\n".
		       "Deze dienen eerst te worden gesloten.",
		       "Open vensters",
		       wxOK|wxICON_ERROR);
	return;
    }
    $self->{d_newdialog} ||= EB::Wx::Tools::NewDialogWiz->new
      ($self, -1,
       "Nieuwe administratie",
       [$config->neww->{xpos},$config->neww->{ypos}],
       [$config->neww->{xwidth},$config->neww->{ywidth}],
      );
    $self->{d_newdialog}->SetSize([$config->neww->{xwidth},$config->neww->{ywidth}]);
    my $ret = $self->{d_newdialog}->ShowModal;
    $self->{d_newdialog}->Destroy;
    $self->{d_newdialog} = undef;
    $self->adapt_menus;
}

# wxGlade: EB::Wx::MainFrame::OnOpen <event_handler>
sub OnOpen {
    my ($self, $event) = @_;
    require EB::Wx::Tools::DbOpenDialog;
    foreach my $win ( grep(/^d_m\S+panel$/, keys(%$self)) ) {
	next unless $self->{$win};
	if ( $self->{$win}->IsShown ) {
	    Wx::MessageBox("Er zijn nog onderhoudsvensters open op de huidige database.\n".
			   "Deze dienen eerst te worden gesloten.",
			   "Open vensters",
			   wxOK|wxICON_ERROR);
	    return;
	}
	$self->{$win}->Destroy;
	delete($self->{$win});
    }
    $self->{d_opendialog} ||= EB::Wx::Tools::DbOpenDialog->new
      ($self, -1,
       "Openen database",
       [$config->openw->{xpos},$config->openw->{ypos}],
       [$config->openw->{xwidth},$config->openw->{ywidth}],
      );
    $self->{d_opendialog}->SetSize([$config->openw->{xwidth},$config->openw->{ywidth}]);
    $self->{d_opendialog}->refresh;
    return unless $self->{d_opendialog}->ShowModal;

    $self->adapt_menus;
    # Refresh existing reports.
    foreach my $win ( grep(/^d_r\S+panel$/, keys(%$self)) ) {
	next unless $self->{$win};
	next unless $self->{$win}->IsShown;
	$self->{$win}->refresh;
    }
}

# wxGlade: EB::Wx::MainFrame::OnExport <event_handler>
sub OnExport {
    my ($self, $event) = @_;
    Wx::LogMessage("Event handler (OnExport) not implemented");
    $event->Skip;
}

# wxGlade: EB::Wx::MainFrame::OnImport <event_handler>
sub OnImport {
    my ($self, $event) = @_;
    Wx::LogMessage("Event handler (OnImport) not implemented");
    $event->Skip;
}

# wxGlade: EB::Wx::MainFrame::OnProperties <event_handler>
sub OnProperties {
    my ($self, $event) = @_;
    require EB::Wx::Tools::PropertiesDialog;
    $self->{d_prpdialog} ||= EB::Wx::Tools::PropertiesDialog->new
      ($self, -1,
       _T("Administratiegegevens"),
       [$config->prpw->{xpos},$config->prpw->{ypos}],
       [$config->prpw->{xwidth},$config->prpw->{ywidth}],
      );
    $self->{d_prpdialog}->SetSize([$config->prpw->{xwidth},$config->prpw->{ywidth}]);
    $self->{d_prpdialog}->refresh;
    $self->{d_prpdialog}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnLogw <event_handler>
sub OnLogw {
    my ($self, $event) = @_;
    if ( $self->{tx_log}->IsShown ) {
	$self->{tx_log}->Show(0);
	$self->{mainframe_menubar}->SetLabel(MENU_LOGW, "Toon log venster");
    }
    else {
	$self->{tx_log}->Show(1);
	$self->{mainframe_menubar}->SetLabel(MENU_LOGW, "Verberg log venster");
    }
    $self->Layout;
}

# wxGlade: EB::Wx::MainFrame::OnLogClean <event_handler>
sub OnLogClean {
    my ($self, $event) = @_;
    $self->{tx_log}->Clear;
}

# wxGlade: EB::Wx::MainFrame::OnRestart <event_handler>
sub OnRestart {
    my ($self, $event) = @_;
    $self->closehandler(@_);
    $::restart++;
    $self->Close(1);
}

# wxGlade: EB::Wx::MainFrame::OnExit <event_handler>
sub OnExit {
    my ($self, $event) = @_;
    $self->closehandler(@_);
    $self->Destroy;
}

################ Menu: Edit ################

# wxGlade: EB::Wx::MainFrame::OnPreferences <event_handler>
sub OnPreferences {
    my ($self, $event) = @_;
    $event->Skip;
}

################ Maintenance ################

# wxGlade: EB::Wx::MainFrame::OnMGbk <event_handler>
sub OnMGbk {
    my ($self, $event) = @_;
    require EB::Wx::Maint::Accounts;
    my $p = "d_maccpanel";
    $self->{$p} ||= EB::Wx::Maint::Accounts->new
      ($self, -1,
       "Onderhoud Grootboekrekeningen",
       [$config->accw->{xpos},$config->accw->{ypos}],
       [$config->accw->{xwidth},$config->accw->{ywidth}],
      );
    $self->{$p}->Move([$config->accw->{xpos},$config->accw->{ypos}]);
    $self->{$p}->SetSize([$config->accw->{xwidth},$config->accw->{ywidth}]);
    $self->{$p}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnMRel <event_handler>
sub OnMRel {
    my ($self, $event) = @_;
    require EB::Wx::Maint::Relaties;
    my $p = "d_mrelpanel";
    $self->{$p} ||= EB::Wx::Maint::Relaties->new
      ($self, -1,
       "Onderhoud Relaties",
       [$config->relw->{xpos},$config->relw->{ypos}],
       [$config->relw->{xwidth},$config->relw->{ywidth}],
      );
    $self->{$p}->SetSize([$config->relw->{xwidth},$config->relw->{ywidth}]);
    $self->{$p}->refresh;
    $self->{$p}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnMBtw <event_handler>
sub OnMBtw {
    my ($self, $event) = @_;
    require EB::Wx::Maint::BTWTarieven;
    my $p = "d_mbtwpanel";
    $self->{$p} ||= EB::Wx::Maint::BTWTarieven->new
      ($self, -1,
       "Onderhoud BTW instellingen",
       [$config->btww->{xpos},$config->btww->{ypos}],
       [$config->btww->{xwidth},$config->btww->{ywidth}],
      );
    $self->{$p}->SetSize([$config->btww->{xwidth},$config->btww->{ywidth}]);
    $self->{$p}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnMStdAcc <event_handler>
sub OnMStdAcc {
    my ($self, $event) = @_;
    require EB::Wx::Maint::StdAccounts;
    my $p = "d_mstdpanel";
    $self->{$p} ||= EB::Wx::Maint::StdAccounts->new
      ($self, -1,
       "Onderhoud Koppelingen",
       [$config->stdw->{xpos},$config->stdw->{ypos}],
       [$config->stdw->{xwidth},$config->stdw->{ywidth}],
      );
    $self->{$p}->SetSize([$config->stdw->{xwidth},$config->stdw->{ywidth}]);
    $self->{$p}->Show(1);
}

################ Menu: Reports ################

# wxGlade: EB::Wx::MainFrame::OnRPrf <event_handler>
sub OnRPrf {
    my ($self, $event) = @_;
    require EB::Wx::Report::BalResProof;
    $self->{d_rprfpanel} ||= EB::Wx::Report::BalResProof->new
      ($self, -1,
       "Proef & Saldibalans",
       [$config->rprfw->{xpos},$config->rprfw->{ypos}],
       [$config->rprfw->{xwidth},$config->rprfw->{ywidth}],
      );
    $self->{d_rprfpanel}->SetSize([$config->rprfw->{xwidth},$config->rprfw->{ywidth}]);
    $self->{d_rprfpanel}->init("prf");
    $self->{d_rprfpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRBal <event_handler>
sub OnRBal {
    my ($self, $event) = @_;
    require EB::Wx::Report::BalResProof;
    $self->{d_rbalpanel} ||= EB::Wx::Report::BalResProof->new
      ($self, -1,
       "Balans",
       [$config->rbalw->{xpos},$config->rbalw->{ypos}],
       [$config->rbalw->{xwidth},$config->rbalw->{ywidth}],
      );
    $self->{d_rbalpanel}->SetSize([$config->rbalw->{xwidth},$config->rbalw->{ywidth}]);
    $self->{d_rbalpanel}->init("bal");
    $self->{d_rbalpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRRes <event_handler>
sub OnRRes {
    my ($self, $event) = @_;
    require EB::Wx::Report::BalResProof;
    $self->{d_rrespanel} ||= EB::Wx::Report::BalResProof->new
      ($self, -1,
       "Resultaat",
       [$config->rresw->{xpos},$config->rresw->{ypos}],
       [$config->rresw->{xwidth},$config->rresw->{ywidth}],
      );
    $self->{d_rrespanel}->SetSize([$config->rresw->{xwidth},$config->rresw->{ywidth}]);
    $self->{d_rrespanel}->init("res");
    $self->{d_rrespanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRGbk <event_handler>
sub OnRGbk {
    my ($self, $event) = @_;
    require EB::Wx::Report::Grootboek;
    $self->{d_rgbkpanel} ||= EB::Wx::Report::Grootboek->new
      ($self, -1,
       "Grootboek",
       [$config->rgbkw->{xpos},$config->rgbkw->{ypos}],
       [$config->rgbkw->{xwidth},$config->rgbkw->{ywidth}],
      );
    $self->{d_rgbkpanel}->SetSize([$config->rgbkw->{xwidth},$config->rgbkw->{ywidth}]);
    $self->{d_rgbkpanel}->init("gbk");
    $self->{d_rgbkpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRJnl <event_handler>
sub OnRJnl {
    my ($self, $event) = @_;
    require EB::Wx::Report::Journaal;
    $self->{d_rjnlpanel} ||= EB::Wx::Report::Journaal->new
      ($self, -1,
       "Journaal",
       [$config->rjnlw->{xpos},$config->rjnlw->{ypos}],
       [$config->rjnlw->{xwidth},$config->rjnlw->{ywidth}],
      );
    $self->{d_rjnlpanel}->SetSize([$config->rjnlw->{xwidth},$config->rjnlw->{ywidth}]);
    $self->{d_rjnlpanel}->init("jnl");
    $self->{d_rjnlpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRBtw <event_handler>
sub OnRBtw {
    my ($self, $event) = @_;
    require EB::Wx::Report::BTWAangifte;
    $self->{d_rbtwpanel} ||= EB::Wx::Report::BTWAangifte->new
      ($self, -1,
       "BTW aangifte",
       [$config->rbtww->{xpos},$config->rbtww->{ypos}],
       [$config->rbtww->{xwidth},$config->rbtww->{ywidth}],
      );
    $self->{d_rbtwpanel}->SetSize([$config->rbtww->{xwidth},$config->rbtww->{ywidth}]);
    $self->{d_rbtwpanel}->init("btw");
    $self->{d_rbtwpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnROpen <event_handler>
sub OnROpen {
    my ($self, $event) = @_;

    warn "Event handler (OnROpen) not implemented";
    $event->Skip;
}

# wxGlade: EB::Wx::MainFrame::OnRDeb <event_handler>
sub OnRDeb {
    my ($self, $event) = @_;
    require EB::Wx::Report::DebCrd;
    $self->{d_rdebpanel} ||= EB::Wx::Report::DebCrd->new
      ($self, -1,
       "Debiteuren",
       [$config->rdebw->{xpos},$config->rdebw->{ypos}],
       [$config->rdebw->{xwidth},$config->rdebw->{ywidth}],
      );
    $self->{d_rdebpanel}->SetSize([$config->rdebw->{xwidth},$config->rdebw->{ywidth}]);
    $self->{d_rdebpanel}->init("deb");
    $self->{d_rdebpanel}->Show(1);
}

# wxGlade: EB::Wx::MainFrame::OnRCrd <event_handler>
sub OnRCrd {
    my ($self, $event) = @_;
    require EB::Wx::Report::DebCrd;
    $self->{d_rcrdpanel} ||= EB::Wx::Report::DebCrd->new
      ($self, -1,
       "Crediteuren",
       [$config->rcrdw->{xpos},$config->rcrdw->{ypos}],
       [$config->rcrdw->{xwidth},$config->rcrdw->{ywidth}],
      );
    $self->{d_rcrdpanel}->SetSize([$config->rcrdw->{xwidth},$config->rcrdw->{ywidth}]);
    $self->{d_rcrdpanel}->init("crd");
    $self->{d_rcrdpanel}->Show(1);
}

################ Menu: Info ################

# wxGlade: EB::Wx::MainFrame::OnDoc <event_handler>
sub OnDoc {
    my ($self, $event) = @_;
    Wx::LaunchDefaultBrowser("http:www.eekboek.nl/docs/index.html");
}

# wxGlade: EB::Wx::MainFrame::OnAbout <event_handler>
sub OnAbout {
    my ($self, $event) = @_;
    Wx::MessageBox("$::appname -- Squirrel Consultancy\n".
		   "wxPerl version $Wx::VERSION\n".
		   "wxWidgets version ".Wx::wxVERSION,
		   "Info...",
		   wxOK,
		   $self);
}

################ End of Menus ################

# end of class EB::Wx::MainFrame

1;

