# generated by wxGlade 0.4cvs on Mon Aug  1 17:42:14 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package main;

our $config;
our $dbh;
our $app;

package AccPanel;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

# begin wxGlade: ::dependencies
use EB::Globals;
use EB::Finance;
use AccTreeCtrl;
use NumericCtrl;
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: AccPanel::new

	$style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{w_acc_frame} = Wx::SplitterWindow->new($self, -1, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER);
	$self->{maint_pane_outer} = Wx::Panel->new($self->{w_acc_frame}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{maint_pane} = Wx::Panel->new($self->{maint_pane_outer}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{sz_btw_staticbox} = Wx::StaticBox->new($self->{maint_pane}, -1, "BTW Tarief" );
	$self->{sz_saldo_staticbox} = Wx::StaticBox->new($self->{maint_pane}, -1, "Saldo" );
	$self->{sz_acc_staticbox} = Wx::StaticBox->new($self->{maint_pane}, -1, "Grootboekrekening" );
	$self->{tree_pane} = Wx::Panel->new($self->{w_acc_frame}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{acc_tree} = AccTreeCtrl->new($self->{tree_pane}, -1, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_NO_LINES|wxTR_HIDE_ROOT|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
	$self->{l_acc_id} = Wx::StaticText->new($self->{maint_pane}, -1, "Nr.", wxDefaultPosition, wxDefaultSize, );
	$self->{l_acc_desc} = Wx::StaticText->new($self->{maint_pane}, -1, "Omschrijving", wxDefaultPosition, wxDefaultSize, );
	$self->{t_acc_id} = NumericCtrl->new($self->{maint_pane}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{t_acc_desc} = Wx::TextCtrl->new($self->{maint_pane}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{rb_balres} = Wx::RadioBox->new($self->{maint_pane}, -1, "Indeling", wxDefaultPosition, wxDefaultSize, ["Balans", "Resultaat"], 0, wxRA_SPECIFY_ROWS);
	$self->{rb_debcrd} = Wx::RadioBox->new($self->{maint_pane}, -1, "Richting", wxDefaultPosition, wxDefaultSize, ["Debet", "Credit"], 0, wxRA_SPECIFY_ROWS);
	$self->{rb_kstomz} = Wx::RadioBox->new($self->{maint_pane}, -1, "Soort", wxDefaultPosition, wxDefaultSize, ["Kosten", "Omzet"], 0, wxRA_SPECIFY_ROWS);
	$self->{l_saldo_opening} = Wx::StaticText->new($self->{maint_pane}, -1, "Opening", wxDefaultPosition, wxDefaultSize, );
	$self->{t_saldo_opening} = Wx::StaticText->new($self->{maint_pane}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{l_saldo_act} = Wx::StaticText->new($self->{maint_pane}, -1, "Actueel", wxDefaultPosition, wxDefaultSize, );
	$self->{t_saldo_act} = Wx::StaticText->new($self->{maint_pane}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{b_accept} = Wx::Button->new($self->{maint_pane_outer}, wxID_APPLY, "");
	$self->{b_reset} = Wx::Button->new($self->{maint_pane_outer}, wxID_UNDO, "");
	$self->{b_cancel} = Wx::Button->new($self->{maint_pane_outer}, wxID_CLOSE, "");

	$self->__set_properties();
	$self->__do_layout();

	Wx::Event::EVT_TEXT($self, $self->{t_acc_id}->GetId, \&OnAccIdChanged);
	Wx::Event::EVT_TEXT($self, $self->{t_acc_desc}->GetId, \&OnAccDescChanged);
	Wx::Event::EVT_RADIOBOX($self, $self->{rb_balres}->GetId, \&OnBalresClicked);
	Wx::Event::EVT_RADIOBOX($self, $self->{rb_debcrd}->GetId, \&OnDebcrdClicked);
	Wx::Event::EVT_RADIOBOX($self, $self->{rb_kstomz}->GetId, \&OnKstomzClicked);
	Wx::Event::EVT_BUTTON($self, wxID_APPLY, \&OnAccept);
	Wx::Event::EVT_BUTTON($self, wxID_UNDO, \&OnReset);
	Wx::Event::EVT_BUTTON($self, wxID_CLOSE, \&OnClose);
	Wx::Event::EVT_SPLITTER_SASH_POS_CHANGED($self, $self->{w_acc_frame}->GetId, \&OnSashPosChanged);

# end wxGlade

	$self->{mew} = "accw";
	$self->{busy} = 0;

	Wx::Event::EVT_CLOSE($self, \&OnClose);
	# Wx::Event::EVT_KILL_FOCUS($self->{t_acc_id}, \&OnAccIdLosesFocus);
	Wx::Event::EVT_IDLE($self, \&OnIdle);

	my $sth = $::dbh->sql_exec("SELECT btw_id,btw_desc FROM BTWTabel ORDER BY btw_id");
	my @a;
	my $i = 0;
	my $fmt = "%2d    %s";
	while ( my $rr = $sth->fetchrow_arrayref ) {
	    while ( $i < $rr->[0] ) {
		$a[$i] = sprintf($fmt, $i, "<< Ongebruikt >>");
		$i++;
	    }
	    $a[$rr->[0]] = sprintf($fmt, $rr->[0], $rr->[1]);
	    $i++;
	}
	$self->{ch_btw} = Wx::Choice->new($self->{maint_pane}, -1,
					  wxDefaultPosition, wxDefaultSize,
					  \@a);
	Wx::Event::EVT_CHOICE($self, $self->{ch_btw}, \&OnBtwChanged);
	$self->{sz_btw}->Add($self->{ch_btw}, 1, wxEXPAND, 0);
	$self->{sz_btw}->Layout;

	$self->{maint_pane}->Enable(0);

	return $self;

}

sub __set_properties {
	my $self = shift;

# begin wxGlade: AccPanel::__set_properties

	$self->{rb_balres}->SetSelection(0);
	$self->{rb_debcrd}->SetSelection(0);
	$self->{rb_kstomz}->Show(0);
	$self->{rb_kstomz}->SetSelection(0);
	$self->{maint_pane}->Enable(0);
	$self->{b_accept}->Enable(0);
	$self->{b_reset}->Enable(0);
	$self->{b_cancel}->SetDefault();

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: AccPanel::__do_layout

	$self->{acc_frame_sizer} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_accx} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sz_acccan} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_acc}= Wx::StaticBoxSizer->new($self->{sz_acc_staticbox}, wxVERTICAL);
	$self->{sz_saldo}= Wx::StaticBoxSizer->new($self->{sz_saldo_staticbox}, wxHORIZONTAL);
	$self->{gr_saldo} = Wx::FlexGridSizer->new(2, 2, 5, 5);
	$self->{sz_btw}= Wx::StaticBoxSizer->new($self->{sz_btw_staticbox}, wxHORIZONTAL);
	$self->{sz_properties} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_id} = Wx::FlexGridSizer->new(2, 2, 5, 5);
	$self->{sz_tree} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_tree}->Add($self->{acc_tree}, 1, wxEXPAND, 0);
	$self->{tree_pane}->SetAutoLayout(1);
	$self->{tree_pane}->SetSizer($self->{sz_tree});
	$self->{sz_tree}->Fit($self->{tree_pane});
	$self->{sz_tree}->SetSizeHints($self->{tree_pane});
	$self->{sz_id}->Add($self->{l_acc_id}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_id}->Add($self->{l_acc_desc}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_id}->Add($self->{t_acc_id}, 0, wxADJUST_MINSIZE, 0);
	$self->{sz_id}->Add($self->{t_acc_desc}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_id}->AddGrowableCol(1);
	$self->{sz_acc}->Add($self->{sz_id}, 0, wxLEFT|wxRIGHT|wxTOP|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_properties}->Add($self->{rb_balres}, 1, wxRIGHT|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_properties}->Add($self->{rb_debcrd}, 1, wxRIGHT|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_properties}->Add($self->{rb_kstomz}, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_acc}->Add($self->{sz_properties}, 0, wxTOP|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_acc}->Add($self->{sz_btw}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{gr_saldo}->Add($self->{l_saldo_opening}, 0, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	$self->{gr_saldo}->Add($self->{t_saldo_opening}, 0, wxLEFT|wxEXPAND|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	$self->{gr_saldo}->Add($self->{l_saldo_act}, 0, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	$self->{gr_saldo}->Add($self->{t_saldo_act}, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	$self->{gr_saldo}->AddGrowableCol(1);
	$self->{sz_saldo}->Add($self->{gr_saldo}, 1, wxBOTTOM|wxEXPAND, 5);
	$self->{sz_acc}->Add($self->{sz_saldo}, 0, wxTOP|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{maint_pane}->SetAutoLayout(1);
	$self->{maint_pane}->SetSizer($self->{sz_acc});
	$self->{sz_acc}->Fit($self->{maint_pane});
	$self->{sz_acc}->SetSizeHints($self->{maint_pane});
	$self->{sz_accx}->Add($self->{maint_pane}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_accx}->Add(1, 5, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_acccan}->Add($self->{b_accept}, 0, wxLEFT|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_acccan}->Add($self->{b_reset}, 0, wxLEFT|wxADJUST_MINSIZE, 5);
	$self->{sz_acccan}->Add(5, 0, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_acccan}->Add($self->{b_cancel}, 0, wxRIGHT|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_accx}->Add($self->{sz_acccan}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{maint_pane_outer}->SetAutoLayout(1);
	$self->{maint_pane_outer}->SetSizer($self->{sz_accx});
	$self->{sz_accx}->Fit($self->{maint_pane_outer});
	$self->{sz_accx}->SetSizeHints($self->{maint_pane_outer});
	$self->{w_acc_frame}->SplitVertically($self->{tree_pane}, $self->{maint_pane_outer}, );
	$self->{acc_frame_sizer}->Add($self->{w_acc_frame}, 1, wxEXPAND, 0);
	$self->SetAutoLayout(1);
	$self->SetSizer($self->{acc_frame_sizer});
	$self->{acc_frame_sizer}->Fit($self);
	$self->{acc_frame_sizer}->SetSizeHints($self);
	$self->Layout();

# end wxGlade

	$self->{w_acc_frame}->SetSashPosition($config->accsash);

}

sub _nf {
    my ($v, $debcrd) = @_;
    numfmtw(abs($v)) . " " .
      (($debcrd ^ ($v < 0)) ? "Credit" : ($v ? "Debet" : ""));
}

sub set_item {
    my ($self, $id, $type, $ctrl, $item) = @_;
    if ( $type == 2 ) {
	$self->set_acc($id, $ctrl, $item);
    }
    else {
	$self->set_vrd($id, $type, $ctrl, $item);
    }
}

sub set_acc {
    my ($self, $id, $ctrl, $item) = @_;

    local($self->{busy}) = 1;
    my $rr = $::dbh->do("SELECT acc_desc, acc_balres, acc_kstomz, acc_debcrd, acc_btw,".
			" acc_balance, acc_ibalance FROM Accounts".
			" WHERE acc_id = ?", $id);

    $self->{_type} = "acc";
    $self->{_ctrl} = $ctrl;
    $self->{_item} = $item;

    $self->{sz_acc}->GetStaticBox->SetLabel
      (($rr->[1] ? "Balans" : "Resultaat")."rekening");
    $self->{t_acc_id}->SetValue($self->{_id} = $id);
    $self->{t_acc_desc}->SetValue($self->{_desc} = $rr->[0]);
    $self->{rb_balres}->SetSelection(!($self->{_balres} = $rr->[1]));
    $self->{rb_kstomz}->SetSelection(!($self->{_kstomz} = $rr->[2]));
    $self->{rb_debcrd}->SetSelection(!($self->{_debcrd} = $rr->[3]));
    $self->{rb_debcrd}->Show(1);
    $self->{sz_properties}->Layout;
    $self->{ch_btw}->SetSelection($self->{_btw} = $rr->[4]);
    $self->{t_saldo_act}->SetLabel(_nf($rr->[5], $rr->[3]));
    $self->{t_saldo_opening}->SetLabel(_nf($rr->[6], $rr->[3]));

    $self->{sz_acc}->Show($self->{sz_btw}, 1);
    $self->{sz_acc}->Show($self->{sz_saldo}, 1);
    $self->{sz_acc}->Layout;

    $self->{b_accept}->Enable(0);
    $self->{b_reset}->Enable(0);
    $self->{maint_pane}->Enable(1);
    $self->{struct} = 0;

    $dbh->trace(1);
}

sub set_vrd {
    my ($self, $id, $type, $ctrl, $item) = @_;

    local($self->{busy}) = 1;
    my $rr = $::dbh->do("SELECT vdi_desc, vdi_balres, vdi_kstomz, vdi_struct".
			" FROM Verdichtingen".
			" WHERE vdi_id = ?", $id);

    $self->{_type} = "vdi";
    $self->{_ctrl} = $ctrl;
    $self->{_item} = $item;

    $self->{sz_acc}->GetStaticBox->SetLabel
      (($rr->[1] ? "Balans" : "Resultaat")."verdichting");
    $self->{t_acc_id}->SetValue($self->{_id} = $id);
    $self->{t_acc_desc}->SetValue($self->{_desc} = $rr->[0]);
    $self->{rb_balres}->SetSelection(!($self->{_balres} = $rr->[1]));
    $self->{rb_kstomz}->SetSelection(!($self->{_kstomz} = $rr->[2]));
    $self->{rb_debcrd}->Show(0);
    $self->{sz_properties}->Layout;

    $self->{sz_acc}->Show($self->{sz_btw}, 0);
    $self->{sz_acc}->Show($self->{sz_saldo}, 0);
    $self->{sz_acc}->Layout;

    $self->{b_accept}->Enable(0);
    $self->{b_reset}->Enable(0);
    $self->{maint_pane}->Enable(1);
    $self->{struct} = 0;

    $dbh->trace(1);
}

sub newentry {
    my ($self, $pid) = @_;

    if ( $self->{b_reset}->IsEnabled ) {
	Wx::Bell;
	return;
    }
    my $rr = $dbh->do("SELECT acc_struct FROM Accounts WHERE acc_id = ?", $pid);
    $pid = $rr->[0] if $rr;
    $rr = $dbh->do("SELECT vdi_balres, vdi_kstomz FROM Verdichtingen WHERE vdi_id = ?", $pid);
    unless ( $rr ) {
	Wx::Bell;
	return;
    }
    $self->{struct} = $pid;

    $self->{_type} = "acc";

    $self->{sz_acc}->GetStaticBox->SetLabel
      (($rr->[0] ? "Balans" : "Resultaat")."rekening");
    $self->{t_acc_id}->SetValue($self->{_id} = "0000");
    $self->{t_acc_desc}->SetValue($self->{_desc} = "");
    $self->{rb_balres}->SetSelection(!($self->{_balres} = $rr->[0]));
    $self->{rb_kstomz}->SetSelection(!($self->{_kstomz} = $rr->[1]));
    $self->{rb_debcrd}->SetSelection(!($self->{_debcrd} = 1));
    $self->{rb_debcrd}->Show(1);
    $self->{sz_properties}->Layout;
    $self->{ch_btw}->SetSelection($self->{_btw} = 0);
    $self->{t_saldo_act}->SetLabel("");
    $self->{t_saldo_opening}->SetLabel("");

    $self->{sz_acc}->Show($self->{sz_btw}, 1);
    $self->{sz_acc}->Show($self->{sz_saldo}, 1);
    $self->{sz_acc}->Layout;

    $self->{b_accept}->Enable(1);
    $self->{b_reset}->Enable(0);
    $self->{maint_pane}->Enable(1);

}

sub curr_id {
    my ($self) = @_;
    $self->{_id};
}

sub set_desc {
    my ($self, $desc) = @_;
    $self->{t_acc_desc}->SetValue($self->{_desc} = $desc);
}

sub changed {
    my ($self) = @_;
    $self->{struct} or return 1;
    $self->{_id} or return 0;
    $self->{t_acc_id}->GetValue or return 1;
    $self->{t_acc_id}->GetValue != $self->{_id} and return 1;
    $self->{t_acc_desc}->GetValue ne $self->{_desc} and return 1;
    $self->{rb_kstomz}->GetSelection == $self->{_kstomz} and return 1;
    $self->{_type} ne "acc" and return 0;
    $self->{rb_debcrd}->GetSelection == $self->{_debcrd} and return 1;
    $self->{ch_btw}->GetSelection != $self->{_btw} and return 1;
}

sub check_id {
    my ($self) = @_;
    my $obj = $self->{t_acc_id};
    return 1 if $obj->GetValue == $self->{_id};
    my $rr = $dbh->do("SELECT COUNT(*) FROM Journal WHERE jnl_acc_id = ?", $self->{_id});
    if ( $rr && $rr->[0] ) {
	Wx::MessageBox("Rekeningnummer ".
		       ($self->{_id}).
		       " is in gebruik en kan daarom niet worden gewijzigd.",
		       "In gebruik",
		       wxOK|wxICON_ERROR);
	local($self->{busy}) = 1;
	$obj->SetValue($self->{_id});
	return 0;
    }
    $rr = $dbh->do("SELECT COUNT(*) FROM Accounts WHERE acc_id = ?", $obj->GetValue);
    if ( $rr && $rr->[0] ) {
	Wx::MessageBox("Rekeningnummer ".
		       ($obj->GetValue).
		       " bestaat reeds.",
		       "In gebruik",
		       wxOK|wxICON_ERROR);
	local($self->{busy}) = 1;
	$obj->SetValue($self->{_id});
	return 0;
    }
    1;
}

# wxGlade: AccPanel::OnSashPosChanged <event_handler>
sub OnSashPosChanged {
    my ($self, $event) = @_;
    $config->set("accsash", $event->GetEventObject->GetSashPosition);
}

# wxGlade: AccPanel::OnAccIdChanged <event_handler>
sub OnAccIdChanged {
    my ($self, $event) = @_;
    return if $self->{busy};
    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnAccIdLosesFocus <event_handler>
sub OnAccIdLosesFocus {
    my ($self, $event) = @_;
    my $obj = $event->GetEventObject;
    return unless $obj->IsModified;

    # This event is tied to t_acc_id, but we need the AccPanel frame.
    my $p = $self->GetParent;
    until ( exists($p->{_id}) ) { $p = $p->GetParent }

    $p->{refocus} = $self unless $p->check_id;

    my $ch = $p->changed;
    $p->{b_accept}->Enable($ch);
    $p->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnIdle <event_handler>
sub OnIdle {
    my ($self, $event) = @_;
    Wx::Window::SetFocus($self->{refocus}), undef $self->{refocus} if $self->{refocus};
}

# wxGlade: AccPanel::OnAccDescChanged <event_handler>
sub OnAccDescChanged {
    my ($self, $event) = @_;
    return if $self->{busy};

    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnBalresClicked <event_handler>
sub OnBalresClicked {
    my ($self, $event) = @_;
    return if $self->{rb_balres}->GetSelection != $self->{_balres};
    $self->{rb_balres}->SetSelection(!$self->{_balres});
    Wx::MessageBox("Om de balans/resultaat eigenschap te wijzigen ".
		   "dient u de rekening in het linker venster ".
		   "te slepen naar de gewenste plaats onder ".
		   ($self->{_balres} ? "Resultaat" : "Balans")."rekeningen",
		   "Niet zo",
		   wxOK|wxICON_ERROR);
}

# wxGlade: AccPanel::OnDebcrdClicked <event_handler>
sub OnDebcrdClicked {
    my ($self, $event) = @_;
    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnKstomzClicked <event_handler>
sub OnKstomzClicked {
    my ($self, $event) = @_;
    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnBtwChanged <event_handler>
sub OnBtwChanged {
    my ($self, $event) = @_;
    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnAccept <event_handler>
sub OnAccept {
    my ($self, $event) = @_;

    return unless $self->check_id;

    my $type = $self->{_type};

    if ( $self->{struct} ) {
	my $sql = "INSERT INTO ".($type eq "acc" ? "Accounts" : "Verdichtingen").
	  " (acc_id,acc_desc,acc_balres,acc_kstomz,acc_debcrd,acc_struct,acc_btw,acc_balance,acc_ibalance)".
	    " VALUES(?,?,?,?,?,?,?,0,0)";
	my @args = ( $self->{_id} = $self->{t_acc_id}->GetValue,
		     $self->{_desc} = $self->{t_acc_desc}->GetValue,
		     $self->{_balres} = 1 - $self->{rb_balres}->GetSelection,
		     $self->{_kstomz} = 1 - $self->{rb_kstomz}->GetSelection,
		     $self->{_debcrd} = 1 - $self->{rb_debcrd}->GetSelection,
		     $self->{struct},
		     $self->{_btw} = $self->{ch_btw}->GetSelection);
	$dbh->sql_exec($sql, @args)->finish;
	$dbh->commit;
	$self->{struct} = 0;
    }
    else {
	my $sql = "UPDATE ".($type eq "acc" ? "Accounts" : "Verdichtingen")." SET";
	my @args;
	my $id = $self->curr_id;

	if ( $self->{t_acc_id}->GetValue ne $self->{_id} ) {
	    $sql .= " ${type}_id = ?,";
	    push(@args, $self->{_id} = $self->{t_acc_id}->GetValue);
	}
	if ( $self->{t_acc_desc}->GetValue ne $self->{_desc} ) {
	    $sql .= " ${type}_desc = ?,";
	    push(@args, $self->{_desc} = $self->{t_acc_desc}->GetValue);
	}
	if ( $self->{rb_kstomz}->GetSelection == $self->{_kstomz} ) {
	    $sql .= " ${type}_kstomz = ?,";
	    push(@args, $self->{_kstomz} = 1 - $self->{rb_kstomz}->GetSelection);
	}
	if ( $type eq "acc" ) {
	    if ( $self->{rb_debcrd}->GetSelection == $self->{_debcrd} ) {
		$sql .= " acc_debcrd = ?,";
		push(@args, $self->{_debcrd} = 1 - $self->{rb_debcrd}->GetSelection);
	    }
	    if ( $self->{ch_btw}->GetSelection != $self->{_btw} ) {
		$sql .= " acc_btw = ?,";
		push(@args, $self->{_btw} = $self->{ch_btw}->GetSelection);
	    }
	}

	if ( @args ) {
	    chop($sql);
	    $sql .= " WHERE ${type}_id = ?";
	    push(@args, $id);
	    $dbh->sql_exec($sql, @args)->finish;
	    $dbh->commit;

	    if ( $self->{_ctrl} ) {
		$self->{_ctrl}->SetItemText($self->{_item}, "$self->{_id}   $self->{_desc}");
		$self->{_ctrl}->SetPlData($self->{_item},
					  GrootboekHandler->new
					  ([$self->{_id}, $self->{_desc}, 2]));
	    }

	}
    }
    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnReset <event_handler>
sub OnReset {
    my ($self, $event) = @_;

    $self->{t_acc_id}->SetValue($self->{_id});
    $self->{t_acc_desc}->SetValue($self->{_desc});
    $self->{rb_debcrd}->SetSelection(!$self->{_debcrd});
    $self->{rb_kstomz}->SetSelection(!$self->{_kstomz});
    $self->{ch_btw}->SetSelection($self->{_btw});

    my $ch = $self->changed;
    $self->{b_accept}->Enable($ch);
    $self->{b_reset}->Enable($ch);
}

# wxGlade: AccPanel::OnClose <event_handler>
sub OnClose {
    my ($self, $event) = @_;
    if ( $self->changed ) {
	my $r = Wx::MessageBox("Er zijn nog wijzigingen, deze zullen verloren gaan.\n".
			       "Venster toch sluiten?",
			       "Annuleren",
			       wxYES_NO|wxNO_DEFAULT|wxICON_ERROR);
	return unless $r == wxYES;
    }
    # Remember position and size.
    @{$config->get($self->{mew})}{qw(xpos ypos xwidth ywidth)} = ($self->GetPositionXY, $self->GetSizeWH);
    # Disappear.
    $self->Show(0);
}

# end of class AccPanel

1;

