# generated by wxGlade 0.4cvs on Mon Aug  1 22:20:40 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

package main;

our $config;
our $app;
our $dbh;

use Wx 0.15 qw[:allclasses];
use strict;
package BtwPanel;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: BtwPanel::new

	$style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{sz_btg_staticbox} = Wx::StaticBox->new($self, -1, "BTW Tariefgroepen" );
	$self->{sz_btw_staticbox} = Wx::StaticBox->new($self, -1, "BTW Tarieven" );
	$self->{gr_btw} = Wx::Grid->new($self, -1);
	$self->{bw_new} = Wx::Button->new($self, -1, "Nieuw");
	$self->{bw_remove} = Wx::Button->new($self, -1, "Verwijderen");
	$self->{bw_apply} = Wx::Button->new($self, -1, "Toepassen");
	$self->{bw_reset} = Wx::Button->new($self, -1, "Herstellen");
	$self->{gr_btg} = Wx::Grid->new($self, -1);
	$self->{bg_new} = Wx::Button->new($self, -1, "Nieuw");
	$self->{bg_remove} = Wx::Button->new($self, -1, "Verwijderen");
	$self->{bg_apply} = Wx::Button->new($self, -1, "Toepassen");
	$self->{bg_reset} = Wx::Button->new($self, -1, "Herstellen");
	$self->{b_cancel} = Wx::Button->new($self, wxID_CANCEL, "Annuleren");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade

	use Wx::Event qw(EVT_MENU EVT_CLOSE);

	my $closehandler = sub {
	    my ($self, $event) = @_;
	    ($config->btww->{xpos}, $config->btww->{ypos}) = $self->GetPositionXY;
	    ($config->btww->{xwidth}, $config->btww->{ywidth})= $self->GetSizeWH;
	};

	EVT_CLOSE($self,
		 sub {
		     my ($self, $event) = @_;
		     $closehandler->(@_);
		     $self->Destroy;
		 });

	use Wx::Event qw(EVT_BUTTON);

	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: BtwPanel::__set_properties

	$self->SetTitle("BTW Tarieven");
	$self->{gr_btw}->CreateGrid(0, 5);
	$self->{gr_btw}->SetRowLabelSize(0);
	$self->{gr_btw}->SetColLabelSize(22);
	$self->{gr_btw}->EnableDragRowSize(0);
	$self->{gr_btw}->SetSelectionMode(wxGridSelectRows);
	$self->{gr_btw}->SetColLabelValue(0, "Code");
	$self->{gr_btw}->SetColLabelValue(1, "Omschrijving");
	$self->{gr_btw}->SetColSize(1, 150);
	$self->{gr_btw}->SetColLabelValue(2, "Perc.");
	$self->{gr_btw}->SetColLabelValue(3, "Groep");
	$self->{gr_btw}->SetColLabelValue(4, "Incl.");
	$self->{gr_btg}->CreateGrid(0, 4);
	$self->{gr_btg}->SetRowLabelSize(0);
	$self->{gr_btg}->SetColLabelSize(22);
	$self->{gr_btg}->EnableDragRowSize(0);
	$self->{gr_btg}->SetSelectionMode(wxGridSelectRows);
	$self->{gr_btg}->SetColLabelValue(0, "Code");
	$self->{gr_btg}->SetColLabelValue(1, "Omschrijving");
	$self->{gr_btg}->SetColSize(1, 150);
	$self->{gr_btg}->SetColLabelValue(2, "Inkoop");
	$self->{gr_btg}->SetColLabelValue(3, "Verkoop");
	$self->{b_cancel}->SetFocus();
	$self->{b_cancel}->SetDefault();

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: BtwPanel::__do_layout

	$self->{sz_btwpanel} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_btwmain} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sz_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_btg}= Wx::StaticBoxSizer->new($self->{sz_btg_staticbox}, wxVERTICAL);
	$self->{sz_btg_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_btw}= Wx::StaticBoxSizer->new($self->{sz_btw_staticbox}, wxVERTICAL);
	$self->{sz_btw_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sz_btw}->Add($self->{gr_btw}, 1, wxLEFT|wxRIGHT|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_btw_buttons}->Add($self->{bw_new}, 0, wxRIGHT|wxADJUST_MINSIZE, 5);
	$self->{sz_btw_buttons}->Add($self->{bw_remove}, 0, wxRIGHT|wxADJUST_MINSIZE, 5);
	$self->{sz_btw_buttons}->Add($self->{bw_apply}, 0, wxADJUST_MINSIZE, 0);
	$self->{sz_btw_buttons}->Add(20, 20, 1, wxADJUST_MINSIZE, 0);
	$self->{sz_btw_buttons}->Add($self->{bw_reset}, 0, wxADJUST_MINSIZE, 0);
	$self->{sz_btw}->Add($self->{sz_btw_buttons}, 0, wxALL|wxEXPAND, 5);
	$self->{sz_btwmain}->Add($self->{sz_btw}, 1, wxEXPAND, 0);
	$self->{sz_btg}->Add($self->{gr_btg}, 1, wxLEFT|wxRIGHT|wxEXPAND|wxADJUST_MINSIZE, 5);
	$self->{sz_btg_buttons}->Add($self->{bg_new}, 0, wxRIGHT|wxADJUST_MINSIZE, 5);
	$self->{sz_btg_buttons}->Add($self->{bg_remove}, 0, wxRIGHT|wxADJUST_MINSIZE, 5);
	$self->{sz_btg_buttons}->Add($self->{bg_apply}, 0, wxADJUST_MINSIZE, 0);
	$self->{sz_btg_buttons}->Add(20, 20, 1, wxADJUST_MINSIZE, 0);
	$self->{sz_btg_buttons}->Add($self->{bg_reset}, 0, wxADJUST_MINSIZE, 0);
	$self->{sz_btg}->Add($self->{sz_btg_buttons}, 0, wxALL|wxEXPAND, 5);
	$self->{sz_btwmain}->Add($self->{sz_btg}, 1, wxEXPAND, 0);
	$self->{sz_btwmain}->Add(20, 5, 0, wxEXPAND, 0);
	$self->{sz_buttons}->Add(20, 20, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{sz_buttons}->Add($self->{b_cancel}, 0, wxALL|wxEXPAND|wxADJUST_MINSIZE|wxFIXED_MINSIZE, 5);
	$self->{sz_btwmain}->Add($self->{sz_buttons}, 0, wxALL|wxEXPAND, 5);
	$self->{sz_btwpanel}->Add($self->{sz_btwmain}, 1, wxALL|wxEXPAND, 5);
	$self->SetAutoLayout(1);
	$self->SetSizer($self->{sz_btwpanel});
	$self->{sz_btwpanel}->Fit($self);
	$self->{sz_btwpanel}->SetSizeHints($self);
	$self->Layout();

# end wxGlade
}

# end of class BtwPanel

1;

